version: "1.0"
info:
  model: int-scaffold
packages:
- name: SerenGH0202Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: upperfspackage
  version: "1.0"
  gitServerName: srcCtrl_shared_bitbucket_Arti
  gitUrl: https://bitbucket.org/testartiibm
  gitUsername: artikhare
  gitBranch: master
services:
- serviceName: project.serengh0202.integrations:bitbucketfs
  packages:
  - name: SerenGH0202Project
    version: "1.0"
  - name: upperfspackage
    version: "1.0"
- serviceName: UpperFSPackage:upperfs
  packages:
  - name: upperfspackage
    version: "1.0"
- serviceName: pub.string:toUpper
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
